# Generated by Django 3.1.7 on 2021-08-26 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.TextField(help_text='nom du produit', max_length=100)),
                ('description', models.TextField(help_text='une description attractif du produit', max_length=200)),
                ('image', models.ImageField(default=0, upload_to=None)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(default='', max_length=200)),
                ('code_postal', models.CharField(default='00000', max_length=6)),
                ('pays', models.CharField(default='France', max_length=50)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SousCategorie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.TextField(help_text='nom du produit', max_length=100)),
                ('description', models.TextField(help_text='une description attractif du produit', max_length=200)),
                ('image', models.ImageField(default=0, upload_to=None)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sauron_ecommerce.categorie')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(help_text='nom du produit', max_length=100, unique=True)),
                ('description', models.TextField(help_text='une description attractif du produit', max_length=200)),
                ('prix', models.FloatField(help_text='le prix du produit en euro')),
                ('date_ajout', models.DateTimeField()),
                ('poids', models.FloatField(help_text='poids du produit en gramme', null=True)),
                ('resolution', models.TextField(choices=[('none', 'none'), ('1080', 'hd'), ('2160', 'hd+'), ('4320', '4k'), ('8640', '8k')])),
                ('image1', models.ImageField(default=0, upload_to=None)),
                ('image2', models.ImageField(default=0, upload_to=None)),
                ('image3', models.ImageField(default=0, upload_to=None)),
                ('image4', models.ImageField(default=0, upload_to=None)),
                ('image5', models.ImageField(default=0, upload_to=None)),
                ('note', models.FloatField(verbose_name=django.db.models.expressions.ValueRange(0, 5))),
                ('souscategorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sauron_ecommerce.souscategorie')),
            ],
            options={
                'ordering': ['nom', 'date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.FloatField(max_length=200)),
                ('produit', models.ManyToManyField(to='sauron_ecommerce.Produit')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sauron_ecommerce.utilisateur')),
            ],
            options={
                'ordering': ['total'],
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payer', models.BooleanField(default=False)),
                ('date_payer', models.DateTimeField()),
                ('panier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sauron_ecommerce.panier')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sauron_ecommerce.utilisateur')),
            ],
            options={
                'ordering': ['date_payer'],
            },
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contenu', models.TextField(max_length=500)),
                ('note', models.IntegerField(null=True)),
                ('produit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sauron_ecommerce.produit')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sauron_ecommerce.utilisateur')),
            ],
            options={
                'ordering': ['utilisateur'],
            },
        ),
    ]
