# Generated by Django 3.1.7 on 2021-08-26 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sauron_ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(default='', max_length=200)),
                ('code_postal', models.CharField(default='00000', max_length=6)),
                ('pays', models.CharField(default='France', max_length=50)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='commentaire',
            options={'ordering': ['profile']},
        ),
        migrations.RemoveField(
            model_name='commentaire',
            name='utilisateur',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='utilisateur',
        ),
        migrations.RemoveField(
            model_name='panier',
            name='utilisateur',
        ),
        migrations.DeleteModel(
            name='Utilisateur',
        ),
        migrations.AddField(
            model_name='commentaire',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sauron_ecommerce.profile'),
        ),
        migrations.AddField(
            model_name='facture',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sauron_ecommerce.profile'),
        ),
        migrations.AddField(
            model_name='panier',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sauron_ecommerce.profile'),
        ),
    ]
