# Generated by Django 3.1.7 on 2021-08-29 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sauron_ecommerce', '0004_auto_20210830_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='note',
            field=models.FloatField(null=True),
        ),
    ]
